name: check_code_quality

on: pull_request

jobs:
  black:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9  # ❗️Pas d’espace autour des deux-points

      - name: Install black
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Run black
        run: black --check --verbose

